#!/bin/bash
# Setup Cloudflare Tunnel for HTTPS

echo "🔧 Cloudflare Tunnel Setup Guide"
echo "================================="
echo ""
echo "This will give you free HTTPS without managing certificates!"
echo ""
echo "Steps:"
echo "1. Install cloudflared on your Hostinger VPS:"
echo "   curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb"
echo "   sudo dpkg -i cloudflared.deb"
echo ""
echo "2. Login to Cloudflare:"
echo "   cloudflared tunnel login"
echo ""
echo "3. Create a tunnel:"
echo "   cloudflared tunnel create hostaway-mcp"
echo ""
echo "4. Create config file /root/.cloudflared/config.yml:"
echo "   tunnel: <TUNNEL-ID-FROM-STEP-3>"
echo "   credentials-file: /root/.cloudflared/<TUNNEL-ID>.json"
echo "   "
echo "   ingress:"
echo "     - hostname: mcp.yourdomain.com"
echo "       service: http://localhost:8080"
echo "     - service: http_status:404"
echo ""
echo "5. Route DNS to tunnel:"
echo "   cloudflared tunnel route dns hostaway-mcp mcp.yourdomain.com"
echo ""
echo "6. Run tunnel as a service:"
echo "   cloudflared service install"
echo "   systemctl start cloudflared"
echo "   systemctl enable cloudflared"
echo ""
echo "✅ Your MCP server will be available at: https://mcp.yourdomain.com"
echo ""
echo "Then use in Claude MCP connector:"
echo "  Name: Hostaway MCP"
echo "  URL: https://mcp.yourdomain.com"
echo "  OAuth fields: (leave empty)"
